#!/bin/sh
#
# Copyright (C) Joel Eriksson <je@clevcode.org> 2014
#

if [ $# -lt 1 ]; then
    echo "Usage: $0 USER [JAILNAME]" >&2
    exit 1
fi

if [ $(id -u) -ne 0 ]; then
    echo "This command must be run as root." >&2
    exit 2
fi

JAILNAME=jail
USERNAME="$1"

if [ $# -ge 2 ]; then
	JAILNAME="$2"
fi

docker inspect "${JAILNAME}_${USERNAME}" >/dev/null 2>&1

if [ $? -ne 0 ]; then
    echo "The ${JAILNAME}_${USERNAME} jail does not exist." >&2
    exit 3
fi

echo "Removing jail for ${USERNAME}..." >&2

docker stop -t 1 ${JAILNAME}_${USERNAME} >/dev/null
docker rm ${JAILNAME}_${USERNAME} >/dev/null
rm -f /etc/sudoers.d/${JAILNAME}_${USERNAME}
usermod -s "" ${USERNAME}

exit 0
