#!/bin/sh
#
# Copyright (C) Joel Eriksson <je@clevcode.org> 2014
#

if [ $# -lt 1 ]; then
    echo "Usage: $0 USER [BASENAME] [SHELL]" >&2
    exit 1
fi

if [ $(id -u) -ne 0 ]; then
    echo "This command must be run as root." >&2
    exit 2
fi

user="$1"

echo "Removing jail for $user..." >&2

docker stop jail_$user >/dev/null 2>&1
docker rm jail_$user >/dev/null 2>&1
rm -f /etc/sudoers.d/jail_$user 2>/dev/null
usermod -s "" $user

exit 0
