#!/bin/sh
#
# Creates a jail-container for the user specified on the command line. Uses
# the ubuntu image by default. Customize this to your needs. In particular,
# the default base image you want to use for your jail, and the commands to
# be executed in the jail after it has been created..
#
# In my case, I remove the SUID/SGID-bit from all SUID and SGID-binaries,
# since I want to minimize the risk of privilege escalation and breaking out
# of the Docker container. Of course, with a kernel vulnerability, it would
# still be game over...
#
# Copyright (C) Joel Eriksson <je@clevcode.org> 2014
#

if [ $# -lt 1 ]; then
    echo "Usage: $0 USER [HOSTNAME] [BASENAME] [IMAGE] [SHELL]" >&2
    exit 1
fi

REAPER=$(which docker-reaper)

if [ "$REAPER" = "" ]; then
    echo "The docker-reaper binary was not found." >&2
    echo "Have you run 'sudo make install' yet?" >&2
    exit 2
fi

# The name of the jail container to use as a base
JAIL_BASENAME=jail

# The image to use when building the initial jail container
JAIL_IMAGE=ubuntu:trusty

# The hostname to use for the jail
JAIL_HOSTNAME=jail

# The shell to assign to the jailed user, within the jail
JAIL_SHELL=/bin/bash

if [ $# -ge 2 ]; then
    JAIL_HOSTNAME="$2"
fi

if [ $# -ge 3 ]; then
    JAIL_IMAGE="$3"
fi

if [ $# -ge 4 ]; then
    JAIL_BASENAME="$4"
fi

if [ $# -ge 5 ]; then
    JAIL_SHELL="$5"
fi

usr="$1"
psw=$(grep "^$usr:" /etc/passwd)

if [ "$psw" = "" ]; then
    echo "No such user: $usr" >&2
    exit 3
fi

uid=$(echo "$psw" | cut -d: -f3)
gid=$(echo "$psw" | cut -d: -f4)
dir=$(echo "$psw" | cut -d: -f6)
grp=$(awk -F: "\$3 == $gid { print \$1 }" < /etc/group)

if [ "$dir" = "/" ]; then
    echo "The home directory for the user you want to create a jail for is /." >&2
    echo "That would be a pretty bad idea..." >&2
    exit 4
fi

docker inspect "$JAIL_BASENAME" >/dev/null 2>&1

if [ $? -ne 0 ]; then
    echo "Could not find jail container, creating..." >&2
    sudo docker run --name="$JAIL_BASENAME" -h "$JAIL_HOSTNAME" -v "$REAPER:/sbin/reaper:ro" -d "$JAIL_IMAGE" /sbin/reaper
    sudo docker-cmd "$JAIL_BASENAME" root apt-get -y update
    sudo docker-cmd "$JAIL_BASENAME" root apt-get -y upgrade
    sudo docker-cmd "$JAIL_BASENAME" root apt-get -y dist-update
    sudo docker-cmd "$JAIL_BASENAME" root apt-get -y install python python-doc man-db manpages manpages-dev tmux
    sudo docker-cmd "$JAIL_BASENAME" root apt-get -y install python-examples binutils binfmt-support cpp
    sudo docker-cmd "$JAIL_BASENAME" root apt-get -y install tmux ctags vim vim-doc vim-scripts vim-nox
    sudo docker-cmd "$JAIL_BASENAME" root sh -c "find / -type f '(' -perm -4000 -o -perm -2000 ')' -exec chmod ug-s {} \\; 2>/dev/null"
    sudo docker stop "$JAIL_BASENAME"
    sudo docker commit "$JAIL_BASENAME" "$JAIL_BASENAME"
fi

docker inspect "${JAIL_BASENAME}_$usr" >/dev/null 2>&1

if [ $? -eq 0 ]; then
    echo "Jail for user already exists, removing..." >&2
    sudo docker stop "${JAIL_BASENAME}_$usr" >/dev/null 2>&1
    sudo docker rm "${JAIL_BASENAME}_$usr" >/dev/null 2>&1
fi

echo "Creating jail for user $usr..." >&2
docker run --name="${JAIL_BASENAME}_${usr}" -h "$JAIL_HOSTNAME" -v "$REAPER:/sbin/reaper:ro" -v "$dir:$dir:rw" -d "$JAIL_BASENAME"

if [ $? -ne 0 ]; then
    echo "Docker failed to create jail. :(" >&2
    exit 5
fi

sudo docker-cmd "${JAIL_BASENAME}_${usr}" root groupadd -g "$gid" "$grp"
sudo docker-cmd "${JAIL_BASENAME}_${usr}" root useradd -s "$JAIL_SHELL" -u "$uid" -g "$gid" -d "$dir" "$usr"

exit 0
